### ISSUE TITLE
Slider w/thumbnail slider on iphone snc issue

### ISSUE THREAD

**Issue by jwbworks** [woocommerce/FlexSlider#1345]
Hello all,

We are having an issue with the flex slider. When you view the slider on say an iphone in landscape. The  slider plays to the second image, and the thumbnail bar shifts. if you click the left nav on the primary image it goes to the 1st image, but the thumbnail bar does not shift back to the first image. 

I see this on the woothemes site ( http://flexslider.woothemes.com/thumbnail-slider.html )

I do see in the code that navigate to is told to go to 0 but the thumbnail bar just doesnt shift.

**Comment by jeffikus** [comment]
Is the correct active thumbnail image selected though? Because from my testing on iOS8.3 that seems to be working 100% - the only issue here is that depending on the actual width of the carousel, the carousel will only move if the item it is moving to select is not fully visible. For example, if there are 3 images visible (1 partially visible, 2 fully) and you navigate using the actual slider, the fully visible carousel images will not cause the carousel to move, only if you are moving to the partially selected image. The carousel "active" item will work though.  

If you are experiencing something different please reopen and upload a screencast of this. Thanks!

**Comment by jwbworks** [comment]
Hi Jeff,

So if you look at http://flexslider.woothemes.com/thumbnail-slider.html  on your iphone, or even take a browser like chrome and get as narrow as possible with out using mobile plugins.
You will notice only 1 1/2 images are visible in the thumbnail bar.
click to the second image either through the main image or the thumbnail bar
Notice the thumbnail bar shifts and highlights the second image and the main image changes to the second image.
Now click the left arrow on the main image the main image updates to the first image
The thumbnail bar highlights the first image, but does not shift back.
This happens no matter how far you progress in the slide show as you go back using the main image left arrow once you get to the second image the thumbnail slider stops moving back.

We are expecting the thumbnail slider to shift to show the first image highlighted.

**Comment by jpstrikesback** [comment]
I'm seeing something similar on mobile (tested on iOS 9.3.x) when an image is swiped left/right, the selected thumb doesn't change

**Comment by jpstrikesback** [comment]
Also seen in #949

**Comment by jeffikus** [comment]
Hi there, I released 2.7.0 last week, please let me know if the issue persists after updating.
