### ISSUE TITLE
Dynamic adding slides "blinks"

### ISSUE THREAD

**Issue by XMMM1** [woocommerce/FlexSlider#1408]
Hello all.

Currently i am testing flexslider for dynamic slides addition. I have implement it successfully but there is a thing that bothers me.

So this is my code for first empty the slider

 var slider = $('.flexslider').data('flexslider');
    while (slider.data('flexslider').count > 0) {
        slider.data('flexslider').removeSlide(0);
    }

and then fill it again
 for (var i = 0; i < showSlides.length; i++) {
        $('.flexslider').data('flexslider').addSlide(<li></li>);
}

The code is called in 
$('.db1').change(function (e) { place where my code is called });

My question is:
Why does addSlide add slides one on top of another and after change() completes flexslider "reinit" itself for showing navigation or not and so on.. Effect that happens is ugly blink where slides are added like
slide 1
slide 2
slide 3
example of my current behaviour: http://postimg.org/image/ctqggb40r/
and after reinit everything ok: http://postimg.org/image/aksh03prl/

on my page, and as i said after change function is complete flexslider reinit itself.

Do anyone have some advice how to add slided directly to slider without "this strange vertical positioning and blinks before reinit"?

If needed i will provide more code and more info.

Thanks in advance for helping me.

**Comment by scattond** [comment]
Hi, you asked for help in an issue that I started. Your problem is not really similar to what was happening to me, but I have a suggestion that you can try. Try giving your slideshow (or the container that your slideshow is inside) a set height, and then make the overflow hidden. That should hide anything that temporarily appears below the slideshow while it loads.
