### ISSUE TITLE
Alt tag and title tag do not render because they are not passed to zoomImg 

### ISSUE THREAD

**Issue by laptopleon** [woocommerce/FlexSlider#1718]
According to W3 principles, every img must have an alt tag, even if this is an empty tag. This is very important to disabled people as well as SEO.

The FlexSlider main image is given a zoomImg class instance on mouse cursor hover. This div shows a zoomed-in copy of the main img, but at the moment without copying the alt tag and title tag along with it.

Could this please be fixed?

**Comment by currentcreative** [comment]
It's weird because I think the Woocommerce team thinks they fixed it in includes/wc-product-functions.php back in 2016 but apparently FlexSlider is breaking it again? Looks like the problem has been persisting for 2 years while the team thinks it's fixed. See here too: https://github.com/woocommerce/woocommerce/issues/10822

Just run any single product page with an image gallery through Wave or SiteImprove extensions and all the thumbnails will get flagged for having no alt text.

**Comment by laptopleon** [comment]
For me, it's reason to avoid sliders as much as possible. People with small businesses hire me for an affordable WP site, but even more important is: optimal SEO. Sliders are appreciated by visitor too of course, but they lack alt-tags and that is bad for your Google listing. Visitors can't appreciate the sliders if they don't see the site in the first place.

**Comment by Ooops-404** [comment]
Is this getting any attention?

**Comment by laptopleon** [comment]
Apparently not.

It's all very interesting to know that according to some "it shouldn't matter for SEO because the text is on the page" but IMHO this is precisely one of those things that makes the difference between a good site and a great site. It's not accidentally causing red flags on the Google Webmaster Tools etc.
