### ISSUE TITLE
Ignored attempt to cancel a touchmove event with cancelable=false

### ISSUE THREAD

**Issue by vndevil** [woocommerce/FlexSlider#1733]
![image](https://user-images.githubusercontent.com/4491523/44247821-44f74680-a211-11e8-96e6-bfe4e2841b6b.png)

I have this error: [Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
When I using Chrome to test resonsive FlexSlider

**Comment by jeffikus** [comment]
Do you have a live url I can see this on?

**Comment by SaintPepsi** [comment]
Hi @jeffikus i'm having the same issue.

Happens when you do a diagonal swipe on the FlexSlider slides.
I think it's meant to prevent the vertical scrolling, but it fails.

You can view the problem here: (Please use mobile view and view the flex slider of the product images.)
https://qbj39pgt9p8z0apd-1828937.shopifypreview.com/collections/neckties/products/diamond-white-liberty-floral-necktie

Have you got any idea why this might happen? using the latest version of FlexSlider.

**Comment by chris-schreyer** [comment]
+1

**Comment by jlipinski3** [comment]
+1 . to reproduce:

- be able to view console errors on a touch-enabled device (devtools inspect devices, touchscreen laptop, etc)
- on the product gallery, touch the main (large) image, and with the image still be touched, squiggle your finger/input around.
- the JS errors will start popping up in the console
