### ISSUE TITLE
Problem with Grid layout

### ISSUE THREAD

**Issue by dalibor-sojic** [woocommerce/FlexSlider#1766]
I need to attach slider to already defined grid layout, ex:

https://jsfiddle.net/sojic/heaufxq6/10/

I need 3 cols to be visible, 2 to scroll

**Comment by shikkaba** [comment]
@liveNetworks the slider adds CSS to it to make sure it works properly. Did you want the grid in one of the slides, or for the slide to be inside one of the grid elements?

If this is an issue with the slider, the developers would need clarification on what the issue is exactly, and what problems you're having. If it's help adding the slider to an existing code base, then maybe asking somewhere like https://stackoverflow.com/ would be more appropriate.

**Comment by liveNetworks** [comment]
Well... I guess you have wrong approach. 

The right way of developing any kind of software is "don't touch what the others have done, extend it with your features".

So, please refactor your code not to touch my css, but wrap it with your element, and play with it.

I have provided jsfiddle link. I have grid layout... need to scroll it. Please take a look the link. Uncomment js part and check what will happen. It is more then obvious.
