### ISSUE TITLE
Not compatible with Google Chrome and rtl mobile browsers 

### ISSUE THREAD

**Issue by riyadhali** [woocommerce/FlexSlider#1802]
2.7.2 Not compatible with Google Chrome and rtl mobile browsers ..
I use jquery.flexslider-min.js
Note:
 Flexlider -rtl 2.6.1
he is working well. but with rtl
not with rtl + ltr

**Comment by dtugend** [comment]
For us this happens due to this code when using in conjunction with WPBakery Page Builder 7.7

https://github.com/woocommerce/FlexSlider/blob/690832b7f972298e76e2965714657a2beec9e35c/jquery.flexslider.js#L918-L922

https://github.com/woocommerce/FlexSlider/blob/690832b7f972298e76e2965714657a2beec9e35c/jquery.flexslider.js#L978-L982

(The isFirefox case would also work fine for Chrome, not sure what purpose it serves.)
