### ISSUE TITLE
does not start on the first slider

### ISSUE THREAD

**Issue by ghost** [woocommerce/FlexSlider#1807]
a cordial greeting and first of all thank you for the wonderful plugin, I am using it to animate a website where the content of the slider is loaded from ajax, the problem that I present is that the slider, instead of initializing in the first slide, starts in the position 0 I share my settings

```
$('#slider').flexslider({
                    keyboard: false,
                    directionNav: true,
                    animation: "slide",
                    randomize: false,
                    reverse: false,
                    controlNav: false,
                    slideshowSpeed: 6000,
                    startAt: 0,
                    initDelay: 300,
                    prevText: "",
                    nextText: "",
})
```

**Comment by havasjeancarlostrabajo** [comment]
![image](https://user-images.githubusercontent.com/96260366/186261408-b3282246-b763-4c8b-826d-d35ca72917dc.png)

As you can see in the screenshot, the slider_0 would be the first slide which has the flex-active-slide class, but that is not the case, because the next slider_1 is shown, because of this I cannot know how to take the height of the element to dynamically adjust the viewport
