### ISSUE TITLE
"slide" mode not working in IE8

### ISSUE THREAD

**Issue by jackmcconnell** [woocommerce/FlexSlider#22]
Tried on several sites and seems to be consistent but "slide" mode doesn't seem to be working properly in IE8. 
It always shows the last slide if set to this. Fade mode works fine though. 

Live site with issue is kevinscullion.com

**Comment by cognitrancraig** [comment]
I have the exact same problem. Stripped everything out, refactured all my code from scratch. Done a full debug and it is caused by **animation: "slide",**

It's not to do with a trailing commar, as I've double checked this and I'm running this line as the first one in my setup. Any fixes would be much appreciated.
