### ISSUE TITLE
itemMargin doesn't work

### ISSUE THREAD

**Issue by jkd77** [woocommerce/FlexSlider#252]
Try as I might, I can't get itemMargin to work. I have a preview site here: http://clients.werremeyer.com/standingpartnership/

I'm using version 2. I have the following initialization code:

jQuery(document).ready(function($)
{  
    // init jquery homepage content slider
    $('.flex-slider').flexslider({
          animation: "slide",
          //controlNav: false,
          directionNav: true,
          prevText: "previous",
          nextText: "next",
          controlsContainer: ".flex-container",
          itemWidth: 150,
          itemMargin: 44
    });
});

Any help would be greatly appreciated.Thanks!

**Comment by webdevbrian** [comment]
Going to agree with the others here ... itemMargin really should take a setting that puts into effect what you declare. If you want to get fancy you could add a secondary parameter for setting either margin, padding, etc. It should be handled like : 

    itemMargin: '10px';

and defaults to margin - the current implementation is confusing at best, and the documentation further adds to that confusion.

**Comment by Happy2host** [comment]
If there's anybody out there having this issue, the best thing to do is have itemWidth include padding. The trick here is to actually using padding and not margin: 

**itemWidth** : _Actual Width + (padding on the left + padding on the right)._

So whatever the margin is you were planning to have, change it to padding instead with the exact same amounts.

**Example.**
Your item width is 125px and the margin on each side is 20px. In your CSS use padding and add box sizing:

box-sizing: border-box; 
padding-left: 20px; /*If you were planning on using margin-left: 20px*/
padding-right: 20px; /*If you were planning on using margin-right: 20px*/

(You'll notice I've added _box-sizing_. I'd recommend you read up on it if you're unfamiliar :) - it inverts the padding, so essentially its pads outward rather than inward, a faux margin if you like)

Then in your JS add the line:
itemWidth: 165,

The itemWidth of 165 is the width (125px) + margin-left (20px) + margin-right (20px).
itemMargin is redundant in my opinion, you don't need to use this. Do correct me if I'm wrong. Happy coding.
