### ISSUE TITLE
begins on last image, jumps to second

### ISSUE THREAD

**Issue by mikeymicrophone** [woocommerce/FlexSlider#292]
When our flexslider carousel loads, it displays the last of our three items.  When I then click to see the next one, it skips over the initial image and shows the second one.

If the window is not in focus (if I have another window active) and then I click into the window with my flexslider, the correct initial image appears.

http://beyondreason.oakley.com

**Comment by ioTus** [comment]
I am experiencing the same issue, Flexslider 2.2.2 within Wordpress 4.1, PHP 5.5.3 environment. I am also noticing that when I click "Previous" from this first (incorrectly) displayed slide, it will show a duplicate of the initial slide for a moment and then hide it, revealing the correct previous slide.

I have noticed that the issue is gone when I disable infinite loop:

`animationLoop: false,`

Not really a "solution", but it removes the horrible UI experience on page load.

**Comment by omurphy27** [comment]
For anyone having the same issue, I upgraded from v2.2.2 (where I was having this problem) to v2.4.0 and it works fine now.

**Comment by jeffikus** [comment]
@omurphy27 thanks for your feedback :) I appreciate that!

**Comment by celsowhite** [comment]
This is still broken in Flexslider v2.6.3. My solution was to change the animation type to 'fade.' Works for me because fade is a cleaner approach for my project.

**Comment by kiwiot** [comment]
Still in FlexSlider v2.6.4 as well
